org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Fabric Properties
  # check these on https://fabricmc.net/develop
  minecraft_version=26.3-rc-3
  loader_version=0.19.5
  fabric_version=0.160.5+26.3

# Mod Properties
  group=com.minelittlepony
  displayname=Mine Little Pony
  authors=Verdana, Rene_Z, Mumfrey, Killjoy1221, Sollace
  description=Mine Little Pony turns players and mobs into ponies. Press F9 in-game to access settings.

# Publishing
  minecraft_version_range=>=26.2 <26.3
  minecraft_version_allow_snapshot=false
  modrinth_loader_type=fabric
  modrinth_project_id=JBjInUXM

# Dependencies
  modmenu_version=21.0.0-beta.1
  kirin_version=1.22.2+26.3
  hd_skins_version=6.16.0+26.3
  mson_version=1.14.0-beta.1+26.3

# Testing
  use_sodium=0
  use_iris=0
  iris_version=1.11.6+26.3
    iris_jcpp_version=1.4.14
    iris_antlr_version=4.13.1
    iris_glsl_version=3.0.0-pre3
  sodium_version=mc26.3-0.9.2
