org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Fabric Properties
  # check these on https://fabricmc.net/develop
  minecraft_version=25w14craftmine
  yarn_mappings=25w14craftmine+build.3
  loader_version=0.16.12
  fabric_version=0.119.7+25w14craftmine

# Mod Properties
  group=com.minelittlepony
  displayname=Mine Little Pony
  authors=Verdana, Rene_Z, Mumfrey, Killjoy1221, Sollace
  description=Mine Little Pony turns players and mobs into ponies. Press F9 ingame to access settings.

# Publishing
  minecraft_version_range=25w14craftmine
  modrinth_loader_type=fabric
  modrinth_project_id=JBjInUXM

# Dependencies
  modmenu_version=14.0.0-rc.2
  kirin_version=1.20.5+1.21.5
  hd_skins_version=6.14.4+25w14craftmine
  mson_version=1.11.2+1.21.4
