@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.minelittlepony.transformation;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
