package com.mumfrey.liteloader.api;

/**
 * LiteLoader Extensible API - Observer base interface
 * 
 * <p>Observers are essentially "core listeners" which are objects which make up
 * the core a of a particular API implementation and sink events generated by
 * the Loader or by other observable components. See the derived interfaces for
 * more detail.</p>
 * 
 * @author Adam Mummery-Smith
 */
public interface Observer 
{
}
